backend:
  name: git-gateway
  branch: main  # Usa la rama principal donde está tu sitio web

media_folder: "images/uploads" # Carpeta donde se guardarán las imágenes
public_folder: "/images/uploads"

collections:
  - name: "novedades"  
    label: "Novedades"
    folder: "novedades" # Carpeta donde se guardarán las notas
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
      - { label: "Imagen destacada", name: "image", widget: "image" }
