backend:
  name: git-gateway
  branch: main

media_folder: "static/images"  
public_folder: "/images"  

collections:
  - name: "notas"
    label: "Notas"
    folder: "content/notas"
    create: true
    slug: "{{fields.titulo | slugify}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }
      - { label: "Fecha de publicación", name: "fecha_publicacion", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Publicado por", name: "publicado_por", widget: "string" }
      - { label: "Rol del autor", name: "rol", widget: "string" }
      - { label: "Contenido", name: "contenido", widget: "markdown" }
