backend:
  name: git-gateway
  branch: main

media_folder: "static/images"  # Carpeta donde se guardarán las imágenes
public_folder: "/images"  # Ruta pública para acceder a las imágenes

collections:
  - name: "notas"
    label: "Notas"
    folder: "content/notas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }  # Imagen no obligatoria
      - { label: "Concepto", name: "concepto", widget: "string" }
      - { label: "Contenido", name: "contenido", widget: "markdown" }
      - { label: "Secciones", name: "secciones", widget: "list", fields: [
          { label: "Subtítulo", name: "subtitulo", widget: "string" },
          { label: "Párrafo", name: "parrafo", widget: "markdown" },
          { label: "Imagen", name: "imagen", widget: "image", required: false }  # Imagen no obligatoria
        ]
      }



